### PR TITLE
Various fixes and improvements

### PR DESCRIPTION
**Pull request by abdullahibnnadjo**
Hi,
I discovered Light recently, but struggled a bit, having issues similar to #22 and #23, and couldn't make it work for some features like setting min cap.
For example, this:
```shell
$ echo 5 | sudo tee /etc/light/mincap/intel_backlight
5
$ sudo light -v3 -Sc 10
Automatic mode -- finding best controller.
/etc/light/mincap/intel_backlight.
/etc/light/mincap/intel_backlight.
error: "file contents are corrupt", in "src/helpers.c" on line 74. # Why? We just set it to 5
error: "could not read value from brightness file", in "src/light.c" on line 581.
intel_backlight.
warning: "could not read controllers brightness file, so controller is not accessible", in "src/light.c" on line 657.
error: "selected controller is not valid, make sure this application is run as root.", in "src/light.c" on line 279.
error: "Initialization failed", in "src/main.c" on line 13.
# Checking the mincap file after that
$ cat -e /etc/light/mincap/intel_backlight
$ # Empty…
```
So I dug into the code, trying to fix what I was facing, and it finally end up into this PR.
Since it contains a bunch of changes, even if commits should be self explanatory, I'll split them below into categories for easier review (some commits may be in multiple locations):
___
### Improvements
**notable for users**
9f12ff9 Makes `-G` operations don't require write permission on files (so without `sudo`)
accee29 light can now run most operations without creating and checking about the `/etc/light` folder
cd70ff5 and 5d3c896 : `-k` option can now be use in conjonction with `-b`, `-m` and `-c`, see readme

**others**
2f14acb, ccff2b5, 6860e11, f288657, 6180bb3

### Fixes
3b2835b, 12e8176, 01e73a2, 9f9d6ae, bcaa7df, 0ecb535, 9032c14, c363ac4, fa2fba1, f62503b, 38c3bf3

### Code related
6aea2b1, 55fe7a9, 9fda8ac, f288657
____
It should fix the issues cited above.
@Anthony25, @jplatte, @abonec, @risingjason, can you check if it works for you?
Please run all your `light` commands with `-v3` flag to check if anything goes wrong (and if you have `valgrind`, also try with it, just in case 👍 )

@haikarainen, some changes may be major ones (semver). Please tell me if I need to change anything.

### CODE REVIEW

**Comment by haikarainen** [comment]
What a lovely pull request, great work! 💯 

Given the size of it, I would like to give it some time, to let people try it out and let it mature a bit.

I'm very sorry for not being able to maintain this repo anymore, I haven't used linux for quite some time right now and I'm also very busy with all kinds of things.

How would you like to become the maintainer of this project? You seem to have really dug in to the project already, and have obviously improved it quite a bit. Let me know what you think!

**Comment by Anthony25** [comment]
@abdullahibnnadjo: Thanks a lot for your patches!

I tested it a little bit, the min cap works great now! Although, I have found a bug when reducing the brightness below the minimum cap: it jumps to the maximum brightness. I am not sure about it, but I think your bug is located (here)[https://github.com/abdullahibnnadjo/light/blob/master/src/light.c#L495]. You might might mean `rawMin` instead of `rawMax`, no?

**Comment by abdullahibnnadjo** [comment]
@haikarainen yep, it definitely needs some review from some people, totally agree
About becoming the maintainer, I'm not sure for the moment, let's see how it goes 👍 

@Anthony25 I don't think this line is the problem, it simply set the specified value to min cap if inferior, or to rawMax if superior to the max.

Can you describe which steps you followed and the output you get from `light` (with `-v3` on each step)?
This is what I get:
```sh
$ sudo rm -rf /etc/light # Cleanup - you shouldn't have to do that, it's only for testing like if we were on a fresh install
$ sudo light -v3 -Sc 5   # Set minimum brightness to 5%, light converts it to 138 in raw units
notice: "Automatic mode -- finding best controller", in "src/light.c" on line 333.
notice: "found 'intel_backlight' controller", in "src/light.c" on line 839.
notice: "executing light on 'intel_backlight' controller", in "src/light.c" on line 446.
notice: "setting minimum cap to 138 (raw)", in "src/light.c" on line 922.

$ sudo light -v3 -Sr 0 # Try to set a value below the minimum
notice: "Automatic mode -- finding best controller", in "src/light.c" on line 333.
notice: "found 'intel_backlight' controller", in "src/light.c" on line 839.
notice: "executing light on 'intel_backlight' controller", in "src/light.c" on line 446.
notice: "specified value is inferior to 138, so adjusting it to this mininum value", in "src/helpers.c" on line 213.
notice: "setting brightness 138 (raw) to controller", in "src/light.c" on line 724.
$ # ok, the value was corrected to min cap

```

**Comment by Anthony25** [comment]
@abdullahibnnadjo: I edited my post after I found exactly where the issue was

**Comment by Anthony25** [comment]
Oh, and of course, you need to remove the unsigned long casting for every call of `LIGHT_CLAMP` if you cast in the macro.

**Comment by abdullahibnnadjo** [comment]
It should be ok now!
I also find a few more things to fix by the way

**Comment by Anthony25** [comment]
Thanks, let me test and tell you if it is ok on my side!

**Comment by Anthony25** [comment]
@abdullahibnnadjo: It looks good to me, thanks a lot!

**Comment by haikarainen** [comment]
yolo

**Pull request merged**
