### PR TITLE
Fixed wrong help display

### PR DESCRIPTION
**Pull request by alexmohr**
The help output was wrong save was restore and vice versa.

### CODE REVIEW

**Comment by igwan** [comment]
Don't forget the readme.

**Comment by CameronNemo** [comment]
Having help, readme, and the manpage contain documentation of every option makes it cumbersome to keep them all in sync when the canonical source (the arguments parser) changes.

**Comment by haikarainen** [comment]
@CameronNemo  again, feel free to do a PR

**Comment by haikarainen** [comment]
Actually, I might just automate this. Not a bad idea!

**Comment by CameronNemo** [comment]
I use go-md2man to create my manpage (and you can create an html page), and just have a non-exhaustive usage message. Your preferences will certainly vary! I dropped help2man because I wanted a more descriptive manpage.

**Comment by troglobit** [comment]
Updated README and man page while merging this.

**Pull request merged**
