### PR TITLE
Use systemd/elogind to set brightness if possible

### PR DESCRIPTION
**Pull request by ikalnytskyi**
Since version 243, systemd-logind supports setting the brightness of an "leds" or "backlight" kernel class device [1]. This method call requires no privileges to call, but a caller can only change the brightness on sessions that are currently active, and they must own the session.

Using systemd/elogind for unprivileged brightness changes is a nice feature to have since it allows to changes brightness without giving explicit permissions to users via groups or setting SUID bit.

Note: It does not work for `auto` backlight device yet. Specifying device via `-s` is required.

[1] https://github.com/systemd/systemd/commit/2a66c2a1eda48433cb7f4ac6e9b9abcf4bd41bf3

### CODE REVIEW

**Comment by haikarainen** [comment]
I'd recommend writing a new enumerator for this one.  sysfs is designed to ever only work by writing to files in the sysfs. Writing a new enumerator called systemd would be a neat feature.

**Comment by ikalnytskyi** [comment]
I have a few questions:

* SystemdD only allows to set brightness, it does not allow to discover devices. Would it be ok to reuse discovering and reading from sysfs?

* What to do with auto target? So far, it's always `sysfs`, but falling back to systemd could be useful for default target too. Creating a new enumerator implies that there's no chance to use systemd for default target. Is that correct?

**Comment by ikalnytskyi** [comment]
Closing since there's not interest from the maintainer. I switched to [brightnessctl](https://github.com/Hummer12007/brightnessctl) because it supports this feature.

**Comment by haikarainen** [comment]
Feel free to write an implementation! I very rarely use Linux (and light) these days..

**Pull request closed without merging**
