### PR TITLE
light/light.c: split out argument parsing and initialization, add comment headers

### PR DESCRIPTION
**Pull request by CameronNemo**
This branch adds DOxygen style comments to each function header that was in light.c, as well as splits the argument parsing and initialization functions into their own separate file.

These changes are intended to improve the readability and maintainability of the project.

### CODE REVIEW

**Comment by CameronNemo** [comment]
The first two commits are **documentation only**.

The third commit has some changes to the functions and their arguments. Overall there is a decrease in lines of code.

**Comment by haikarainen** [comment]
I dont feel like this rewrite makes any sense at all. It feels like it really doesnt fill any purpose. Imo, it makes the code even more cluttered and unreadable.

I get that youre trying to remove some clutter that has been added through the years, but this really just replaces it with even more clutter.

**Comment by CameronNemo** [comment]
By simply adding comments? Would you mind if I put them in the header file?

**Comment by haikarainen** [comment]
No, comments are always good, I was referring to the splitting up functionality between files etc. You arent _really_ removing loc, youre simply moving them, whilst at the same time adding files and code complexity. Long source files arent neccesarily a bad thing. I very much believe the KISS-principle is applicable here

I hope you dont take my criticism too harshly, I very much appreciate your hard work and effort, and I encourage you to continue contributing! ❤️

**Comment by CameronNemo** [comment]
How do you feel about directly calling parseArguments from main and doing the version/help dialog at that point?

**Comment by CameronNemo** [comment]
I personally dislike the postponing of printHelp and printVersion, as well as the pass through of the command line arguments.

**Comment by haikarainen** [comment]
Again, the structure of this application is far from optimal. I think a rewrite would be better honestly. It's just all very messy. Doing small changes here and there will only make it more messy.

**Pull request closed without merging**
