### PR TITLE
Mixed up options in help

### PR DESCRIPTION
**Pull request by Feresey**
image

### CODE REVIEW

**Comment by haikarainen** [comment]
Please elaborate, where is the conflict?

**Comment by Feresey** [comment]
Confused save and load options.  The option O should save (so says --help).  In fact, it loads.  Well, the second option also does the opposite

**Comment by Feresey** [comment]
Hmm, wait

**Comment by Feresey** [comment]
I think I got something wrong

**Comment by Feresey** [comment]
In about 20 minutes I’ll get home and check it again

**Comment by Feresey** [comment]
haha, look at this 
image

Blame PKGBUILD on AUR, I will write there.
Your program is super!

**Pull request closed without merging**
