### PR TITLE
Remove trailing whitespaces

### PR DESCRIPTION
**Pull request by blochl**
Removing the trailing whitespaces, that can be quite annoying for people who use editors which show them. Additionally, it is a good practice to avoid them.

### CODE REVIEW

**Comment by blochl** [comment]
@haikarainen, can you please tell why did you close this PR? (I've fixed the conflict that was in the initial one - my fork was out of date.)

**Comment by haikarainen** [comment]
Because its practically low-effort spam. Always feel free to contribute in meaningful ways!

**Comment by blochl** [comment]
It is low-effort, but it would help me a lot working on it locally. That's how I see the code now:

screenshot

As you can see, it's quite annoying. And there is absolutely no reason for keeping them. You're the project owner, so it's your decision, obviously, but I'd appreciate if you'd consider including this cosmetic fix.

**Comment by haikarainen** [comment]
Honestly, this is an issue with your editor (or its configuration), not the project itself. Those red blocks are completely obnoxious lol.

**Comment by blochl** [comment]
I set my editor like this on purpose, to alert me of trailing whitespaces. Cause they are a nasty thing. For example: https://softwareengineering.stackexchange.com/questions/121555/why-is-trailing-whitespace-a-big-deal

Besides, they make the files a few bytes larger. :) (But that's obviously not the main reason I dislike them)

**Comment by haikarainen** [comment]
Really, the only practical reason I can see that you dislike them, is because you've set your editor to have big red blocks where they are. Disable that feature and I'm sure you'll be fine!

I read the link, but I still see no valid points that are worthy of clicking the "merge" button. I could go on about why, but it's such a shitty little thing, I'm just going to drop it now. I suggest you do too, because your editor looks horrible because of it.

**Pull request closed without merging**
